name: Spellcheck
on:
  pull_request:
    paths:
    - '**/*.md'
  push:
    paths:
    - '**/*.md'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Spelling
      uses: rojopolis/spellcheck-github-actions@v0.26.0
